# Site settings
title: Chico State Web Dev and Design Club
email: csuwebdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Become a better web developer, network with others, build teamwork.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://csuwebdev.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile']
